name: ai_smart_health
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - spyder>=5.*
  - scikit-learn
  - seaborn
  - shap
  - tensorflow
  - tqdm
  - pytest
  - pip:
    - opencv-python
