name: ai4sh-gpu
dependencies:
  - numpy
  - pandas
  - pip
  - scikit-learn
  - seaborn
  - tensorflow-gpu
  - tqdm
  - pytest
  - pip:
    - jupyter
    - lifelines
    - matplotlib
    - opencv-python
    - pydotplus
    - spyder>=5.*
    - lightgbm
